2025-04-17 20:39:09,388 ERROR: Exception on / [GET] [in /var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/www/u3085459/data/www/sosmark.ru/app.py", line 203, in index
    return render_template("index.html", form=form, result=result)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/base.html", line 17, in template
    <meta property="og:title" content="{% block title %}ЧС Сосмарка{% endblock %}">
jinja2.exceptions.TemplateAssertionError: block 'title' defined twice
2025-04-17 20:39:09,937 ERROR: Exception on / [GET] [in /var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/www/u3085459/data/www/sosmark.ru/app.py", line 203, in index
    return render_template("index.html", form=form, result=result)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/base.html", line 17, in template
    <meta property="og:title" content="{% block title %}ЧС Сосмарка{% endblock %}">
jinja2.exceptions.TemplateAssertionError: block 'title' defined twice
2025-04-17 20:39:10,395 ERROR: Exception on / [GET] [in /var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/www/u3085459/data/www/sosmark.ru/app.py", line 203, in index
    return render_template("index.html", form=form, result=result)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/base.html", line 17, in template
    <meta property="og:title" content="{% block title %}ЧС Сосмарка{% endblock %}">
jinja2.exceptions.TemplateAssertionError: block 'title' defined twice
2025-04-17 20:39:40,915 ERROR: Exception on / [GET] [in /var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/var/www/u3085459/data/www/sosmark.ru/app.py", line 203, in index
    return render_template("index.html", form=form, result=result)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/var/www/u3085459/data/flaskenv/lib/python3.9/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/www/u3085459/data/www/sosmark.ru/templates/base.html", line 17, in template
    <meta property="og:title" content="{% block title %}ЧС Сосмарка{% endblock %}">
jinja2.exceptions.TemplateAssertionError: block 'title' defined twice
